version: '3.8'
services:
  server:
    user: root
    container_name: team-roll-server
    image: team-roll-server:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5001:5001"
    volumes:
      - /app/node_modules
      - ~/docker-certs:/etc/letsencrypt/live/lmru-returns.ru:ro
    environment:
      - NODE_ENV=production


