FROM node:alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build


WORKDIR /app/client

COPY client/package*.json ./

RUN npm install

RUN npm run build


WORKDIR /app

EXPOSE 5001

# Start the server
CMD ["node", "./dist/app.js"]
